// Copyright © 2024 KubeStack-AI Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

import "time"

// ExecutionStrategy defines the method for executing the steps in a plan.
type ExecutionStrategy string

const (
	// SerialExecution specifies that steps should be executed one by one, in the order they appear.
	SerialExecution ExecutionStrategy = "serial"
	// ParallelExecution specifies that steps with no interdependencies can be executed concurrently.
	ParallelExecution ExecutionStrategy = "parallel"
)

// ExecutionPlan is a detailed, ordered list of steps to be executed to resolve one or more issues.
// It is generated by the ExecutionPlanner, annotated with a risk assessment, and then presented
// to the user for review before execution.
type ExecutionPlan struct {
	// ID is the unique identifier for this execution plan.
	ID string `json:"id" yaml:"id"`
	// Strategy defines how the steps in the plan should be executed (e.g., serial, parallel).
	Strategy ExecutionStrategy `json:"strategy" yaml:"strategy"`
	// Steps is the ordered list of actions to be performed.
	Steps []*ExecutionStep `json:"steps" yaml:"steps"`
	// Risk is the assessed risk level and description for the entire plan.
	Risk *RiskAssessment `json:"risk,omitempty" yaml:"risk,omitempty"`
	// RollbackPlan contains the steps needed to revert the plan's actions in case of failure.
	RollbackPlan *RollbackPlan `json:"rollbackPlan,omitempty" yaml:"rollbackPlan,omitempty"`
}

// ExecutionStep represents a single, atomic action within an execution plan.
// Its status is updated in real-time as the execution manager processes the plan.
type ExecutionStep struct {
	// ID is the unique identifier for this step.
	ID string `json:"id" yaml:"id"`
	// Name is a short, human-readable name for the step.
	Name string `json:"name" yaml:"name"`
	// Description provides more detail on what the step does and why.
	Description string `json:"description" yaml:"description"`
	// Action is the concrete, executable action to be performed for this step.
	Action *FixAction `json:"action" yaml:"action"`
	// DependsOn lists the IDs of other steps that must be completed successfully before this step can start.
	DependsOn []string `json:"dependsOn,omitempty" yaml:"dependsOn,omitempty"`
	// Status indicates the current state of the step (e.g., "Pending", "Running", "Success", "Failed").
	Status StepStatus `json:"status" yaml:"status"`
	// Result holds a summary of the output or outcome of the step after execution.
	Result string `json:"result,omitempty" yaml:"result,omitempty"`
}

// ExecutionResult contains the overall outcome and detailed logs of an executed plan.
// This struct is the final artifact of an execution run.
type ExecutionResult struct {
	// PlanID is the ID of the execution plan that was run.
	PlanID string `json:"planId" yaml:"planId"`
	// Status is the final status of the execution (e.g., "Success", "Failed", "PartialSuccess").
	Status ExecutionStatus `json:"status" yaml:"status"`
	// StartTime is the UTC time when the execution began.
	StartTime time.Time `json:"startTime" yaml:"startTime"`
	// EndTime is the UTC time when the execution concluded.
	EndTime time.Time `json:"endTime" yaml:"endTime"`
	// StepResults contains the final state of each step in the plan after execution.
	StepResults []*ExecutionStep `json:"stepResults" yaml:"stepResults"`
	// Logs is a list of all log entries generated during the execution, providing a detailed audit trail.
	Logs []*ExecutionLog `json:"logs,omitempty" yaml:"logs,omitempty"`
}

// RiskLevel defines the severity of a potential risk.
type RiskLevel int

const (
	RiskLevelLow RiskLevel = iota
	RiskLevelMedium
	RiskLevelHigh
	RiskLevelCritical
)

// String makes RiskLevel implement the Stringer interface.
func (rl RiskLevel) String() string {
	return [...]string{"Low", "Medium", "High", "Critical"}[rl]
}

// RiskAssessment provides a summary of the potential risks associated with an
// execution plan.
type RiskAssessment struct {
	TotalScore       int       `json:"total_score"`
	MaxSeverity      RiskLevel `json:"max_severity"`
	RequiresApproval bool      `json:"requires_approval"`
	Description      string    `json:"description"`
}

// StepStatus defines the possible states of an execution step.
type StepStatus string

const (
	StepStatusPending StepStatus = "Pending"
	StepStatusRunning StepStatus = "Running"
	StepStatusSuccess StepStatus = "Success"
	StepStatusFailed  StepStatus = "Failed"
	StepStatusSkipped StepStatus = "Skipped"
)

// RollbackPlan defines the strategy and steps required for reverting a failed execution.
// This is a critical component for ensuring the safety and transactional integrity of automated fixes.
type RollbackPlan struct {
	// Strategy defines the rollback approach (e.g., "Automatic", "Manual").
	Strategy string `json:"strategy" yaml:"strategy"`
	// Steps is a list of compensating actions to revert the changes made by the execution plan.
	Steps []*ExecutionStep `json:"steps" yaml:"steps"`
}

// ExecutionLog records a single, timestamped log entry generated during the execution of a plan.
type ExecutionLog struct {
	// Timestamp is the UTC time when the log entry was created.
	Timestamp time.Time `json:"timestamp" yaml:"timestamp"`
	// StepID is the ID of the execution step that generated this log entry.
	StepID string `json:"stepId,omitempty" yaml:"stepId,omitempty"`
	// Message is the content of the log entry.
	Message string `json:"message" yaml:"message"`
	// Level is the severity level of the log (e.g., "Info", "Warn", "Error").
	Level string `json:"level" yaml:"level"`
}

// ExecutionMetrics contains performance metrics related to the execution process itself.
type ExecutionMetrics struct {
	// TotalDuration is the total time taken to execute the plan.
	TotalDuration time.Duration `json:"totalDuration" yaml:"totalDuration"`
	// StepDurations maps each step ID to the time it took to execute.
	StepDurations map[string]time.Duration `json:"stepDurations,omitempty" yaml:"stepDurations,omitempty"`
}

// ConfigChange represents a structured, safe way to describe a configuration change
// to be applied to a file, avoiding the risks of raw shell commands like `sed` or `awk`.
type ConfigChange struct {
	// File is the full path to the configuration file to be modified.
	File string `json:"file" yaml:"file"`
	// Key is the configuration key or parameter to be changed.
	Key string `json:"key" yaml:"key"`
	// Value is the new value to be assigned to the key.
	Value string `json:"value" yaml:"value"`
}

//Personal.AI order the ending
